string status
float64 g_x
float64 g_y
float64 g_z
float64 g_roll
float64 g_pitch
float64 g_yaw
float64 g_vx
float64 g_vy
float64 g_vz
float64 g_vroll
float64 g_vpitch
float64 g_vyaw
float64 c_x
float64 c_y
float64 c_z
float64 c_roll
float64 c_pitch
float64 c_yaw
float64 c_vx
float64 c_vy
float64 c_vz
float64 c_vroll
float64 c_vpitch
float64 c_vyaw
---
float64 x
float64 y
float64 z
float64 roll
float64 pitch
float64 yaw
float64 vx
float64 vy
float64 vz
float64 vroll
float64 vpitch
float64 vyaw